FROM oven/bun:latest as builder

WORKDIR /mnt

COPY . .

RUN bun install

RUN bunx prisma db pull

RUN bunx prisma generate

RUN bun run build

FROM oven/bun:latest as runner

WORKDIR /mnt

COPY --from=builder /mnt/dist ./dist

COPY --from=builder /mnt/node_modules ./node_modules

COPY --from=builder /mnt/package.json .

COPY --from=builder /mnt/bun.lockb .

COPY --from=builder /mnt/prisma ./prisma

EXPOSE 8000

CMD ["bun", "dist/index.js"]