FROM oven/bun:latest as builder

WORKDIR /mnt

COPY . .

RUN bun install

RUN bun run build

FROM thistine/simple-http-server as runner

WORKDIR /mnt

COPY --from=builder /mnt/dist ./static

ENTRYPOINT [ "/app/serviceapifrontend" ]

EXPOSE 4000