import type { Metadata } from "next";
import { Inter, Noto_Sans_Thai } from "next/font/google";
import { Button, ConfigProvider } from "antd";
import "./globals.css";
const noto_sans = Noto_Sans_Thai({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={noto_sans.className}>{children}</body>
    </html>
  );
}
