on:
  pull_request:
    branches: []
  push:
    branches:
      - main

name: stfu
jobs:
  checking-admin:
    name: checking-admin
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version:
          - latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Run lint
        run: yarn lint
        working-directory: ./admin
      - name: Run build
        run: bun run build
        working-directory: ./admin

  checking-public:
    name: checking-public
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Run lint
        run: yarn lint
        working-directory: ./public
      - name: Run build
        run: bun run build
        working-directory: ./public

  checking-backend:
    name: checking-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      - name: Run build
        run: bun run build
        working-directory: ./backend
