on:
  pull_request:
    branches: []
  push:
    branches:
      - main
name: stfu
jobs:
  checking-admin:
    name: checking-admin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: cd ./admin
      - run: bun run lint
      - run: bun run build

  checking-public:
    name: checking-public
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: cd ./public
      - run: bun run lint
      - run: bun run build

  checking-backend:
    name: checking-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: cd ./backend
      - run: bun run lint
