name: Pull Request Lint and Build Check
on:
    pull_request:
        branches:
            - '*'

jobs:
    checking-admin:
        name: checking-admin
        runs-on: ubuntu-latest
        strategy:
            matrix:
                bun-version:
                    - latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Install dependencies
              run: bun install
              working-directory: ./admin
            - name: Run lint
              run: bun run lint
              working-directory: ./admin
            - name: Run build
              run: bun run build
              working-directory: ./admin

    checking-public:
        name: checking-public
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Install dependencies
              run: bun install
              working-directory: ./public
            - name: Run lint
              run: bun run lint
              working-directory: ./public
            - name: Run build
              run: bun run build
              working-directory: ./public

    checking-backend:
        name: checking-backend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: ${{ matrix.bun-version }}
            - name: Install dependencies
              run: bun install
              working-directory: ./backend
            - name: Run lint
              run: bun run lint
              working-directory: ./backend
